site_name: VanillaPlus
site_description: Documentation for the VanillaPlus Paper Minecraft plugin
site_url: http://xodiumsoftware.github.io/VanillaPlus
repo_name: XodiumSoftware/VanillaPlus
repo_url: https://github.com/XodiumSoftware/VanillaPlus
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: amber
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - tables
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Modules:
      - modules/index.md
      - Book: modules/book.md
      - Chiseled Bookshelf: modules/chiseledbookshelf.md
      - Chat: modules/chat.md
      - Dimensions: modules/dimensions.md
      - Entity: modules/entity.md
      - Inventory: modules/inventory.md
      - Locator: modules/locator.md
      - MOTD: modules/motd.md
      - Openable: modules/openable.md
      - Player: modules/player.md
      - Rune: modules/rune.md
      - Scoreboard: modules/scoreboard.md
      - Server Info: modules/server-info.md
      - Sit: modules/sit.md
      - Tameable: modules/tameable.md
  - Enchantments: enchantments.md
  - Recipes: recipes.md
  - Runes: modules/rune.md
  - Commands & Permissions: commands.md
  - Configuration: configuration.md
