name: ${name}
version: ${version}
main: org.xodium.vanillaplus.VanillaPlus
description: ${description}
api-version: ${apiVersion}
authors: ${authors}
dependencies:
  server:
    WorldEdit:
      load: BEFORE
      required: true
      join-classpath: true