name: VanillaPlus
version: 1.21.9
main: org.xodium.vanillaplus.VanillaPlus
description: Minecraft plugin that enhances the base gameplay
api-version: 1.21.9
author: Xodium
dependencies:
  server:
    WorldEdit:
      load: BEFORE
      required: false
      join-classpath: true
