name: VanillaPlus
version: 1.1.4
main: org.xodium.vanillaplus.VanillaPlus
description: Minecraft plugin that enhances the base gameplay.
api-version: 1.21.3
authors:
  - XodiumSoftware
permissions:
  vanillaplus.doubledoors:
    description: Allows to open double doors with one click
    default: true
  vanillaplus.knock:
    description: Allows to knock on doors using left-click
    default: true
  vanillaplus.autoclose:
    description: Allows players to have their doors close automatically
    default: true
