name: VanillaPlus
version: 1.21.8-1
main: org.xodium.vanillaplus.VanillaPlus
description: Minecraft plugin that enhances the base gameplay
api-version: 1.21.8
author: Xodium
dependencies:
  server:
    WorldEdit:
      load: BEFORE
      required: false
      join-classpath: true