name: VanillaPlus
version: ${version}
main: org.xodium.vanillaplus.VanillaPlus
description: ${description}
api-version: 1.21.8
author: ${author}
dependencies:
  server:
    WorldEdit:
      load: BEFORE
      required: false
      join-classpath: true
    CrazyAdvancementsAPI:
      load: BEFORE
      required: false
      join-classpath: true