name: VanillaPlus
version: ${version}
main: org.xodium.vanillaplus.VanillaPlus
description: ${description}
api-version: 1.21.5
authors:
  - XodiumSoftware
dependencies:
  server:
    WorldEdit:
      load: BEFORE
      required: true
      join-classpath: true