name: ${name}
version: ${version}
main: org.xodium.vanillaplus.VanillaPlus
description: ${description}
api-version: ${apiVersion}
authors: ${authors}
dependencies:
  server:
    WorldEdit:
      load: BEFORE
      required: true
      join-classpath: true
permissions:
  vanillaplus.use:
    description: Allows use of the VanillaPlus commands
    default: true
  vanillaplus.reload:
    description: Allows reloading the VanillaPlus plugin
    default: op
  vanillaplus.gui.faq:
    description: Allows viewing the VanillaPlus FAQ
    default: true
  vanillaplus.gui.dims:
    description: Allows viewing the VanillaPlus dimensions
    default: true
  vanillaplus.gui.settings:
    description: Allows viewing the VanillaPlus settings
    default: true
  vanillaplus.gui.skins:
    description: Allows viewing the VanillaPlus skins
    default: true