name: VanillaPlus
version: 1.8.0
main: org.xodium.vanillaplus.VanillaPlus
description: Minecraft plugin that enhances the base gameplay
api-version: 1.21.5
authors:
  - XodiumSoftware
dependencies:
  server:
    WorldEdit:
      load: BEFORE
      required: true
      join-classpath: true