name: VanillaPlus
version: 1.0.0
main: org.xodium.vanillaplus.VanillaPlus
description: Minecraft plugin that enhances the base gameplay.
api-version: 1.21.3
authors: [ XodiumSoftware ]
dependencies:
  server:
    WorldEdit:
      load: BEFORE
      required: true
      join-classpath: true
permissions:
  VanillaPlus.reload:
    description: Allows to reload the configuration
    default: op
  VanillaPlus.doubledoors:
    description: Allows to open double doors with one click
    default: true
  VanillaPlus.knock:
    description: Allows to knock on doors using left-click
    default: true
  VanillaPlus.autoclose:
    description: Allows players to have their doors close automatically
    default: true
