name: ${name}
version: ${version}
main: org.xodium.vanillaplus.VanillaPlus
description: ${description}
api-version: ${apiVersion}
authors: ${authors}
dependencies:
  server:
    CMI:
      load: BEFORE
      required: true
      join-classpath: true
    CMILib:
      load: BEFORE
      required: true
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    WorldEdit:
      load: BEFORE
      required: true
      join-classpath: true