name: ${project.name}
description: ${project.description}
main: ${project.main}
version: ${project.version}
api-version: ${project.api.version}
authors:
  - XodiumSoftware
database: false
load: ${project.load}
commands:
  vanillaplus:
    description: Main command for VanillaPlus
    permission: vanillaplus.gui
    usage: /vanillaplus
permissions:
  vanillaplus.gui:
    description: Allows to open the VanillaPlus GUI
    default: op
  vanillaplus.doubledoors:
    description: Allows to open double doors with one click
    default: true
  vanillaplus.knock:
    description: Allows to knock on doors using left-click
    default: true
  vanillaplus.autoclose:
    description: Allows players to have their doors close automatically
    default: true
