package org.xodium.vanillaplus.data

import java.util.*

/**
 * Represents the data structure for a quest in the game.
 * @property id The unique identifier for the quest, generated by default if not provided.
 * @property task The description of the task or objective of the quest.
 * @property reward The description of the reward granted upon completing the quest.
 * @property completed Indicates whether the quest is completed. Defaults to false.
 */
data class QuestData(
    val id: UUID = UUID.randomUUID(),
    val task: String,
    val reward: String,
    val completed: Boolean = false,
)
