name: Xodium CI/CD - Docs

on:
  push:
    branches: [ main ]
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "requirements-docs.txt"
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v6.0.2

      - id: setup-python
        name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - id: install-deps
        name: Install dependencies
        run: pip install -r requirements-docs.txt

      - id: deploy
        name: Deploy docs
        run: mkdocs gh-deploy --force
